#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED by BEEHub converter -- DO NOT EDIT BY HAND
Source: Projects/OLM/paradigm/presentation/OLM_paradigm/SET_A/Locato30_VersionA_fMRI.exp
        + sce/00_Instr_1.sce, sce/01_Prac.sce, sce/02_Instr_2.sce,
          sce/03_learning.sce, sce/04_Instr_3.sce, sce/04_AFC.sce, sce/05_AFC.sce
Manifest: Agent/manifests/OLM_SET_A.yaml
Model:  qwen3-coder:30b @ AppHubAI    generated: 2026-07-20

This is the German variant. It follows the manifest as the source of truth
for block structure, trial counts, timing, and stimulus organisation.
All logic is identical to the English version; only displayed text is translated.
"""

import os, random, datetime, csv, glob
from psychopy import visual, core, event, gui

# ── Provenance ─────────────────────────────────────────────────────────────────
# All durations here are in SECONDS (converted from ms in the .sce files).
# fMRI pulse synchronisation was intentionally removed (see manifest).
# Block order is shuffled at runtime with the same two constraints as the PCL:
#   1. First block must not be control
#   2. No two adjacent blocks may have the same type
# The realised order is logged to the CSV.

# ── Paths ──────────────────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
def _p(*parts): return os.path.join(_HERE, *parts)

STIM_LEARN_DIRS = [_p("Stimuli","learning",f"block{i}") for i in range(1,5)]
STIM_CTRL_DIRS  = [_p("Stimuli","control", f"block{i}") for i in range(1,3)]
STIM_AFC_DIR    = _p("Stimuli","AFC")
STIM_BUBBLES    = _p("Stimuli","bubbles")
STIM_INSTR_DIR  = _p("Stimuli","instr")
DATA_DIR        = _p("data")

# ── Timing (seconds) -- converted from ms ──────────────────────────────────────
# Source: 03_learning.sce trial duration = 2500 ms
TRIAL_DUR    = 2.500   # stimulus + response window
# Source: 03_learning.sce FeedTrial.set_duration(2000)
FEEDBACK_DUR = 2.000   # correct-position feedback
# Source: 03_learning.sce fixTrial.set_duration(4500)
FIX_DUR      = 4.500   # inter-block fixation (fMRI baseline)
# Source: bubbles info screen 4500 ms
BUBBLE_DUR   = 4.500
# Source: intro flash 100 ms
INTRO_DUR    = 0.100

# ── Experiment dialog ──────────────────────────────────────────────────────────
exp_info = {"Teilnehmer": "", "Sitzung": "1", "fMRI-Modus": False}
dlg = gui.DlgFromDict(exp_info, title="OLMM Set A", sortKeys=False)
if not dlg.OK: core.quit()

participant = exp_info["Teilnehmer"]
session     = exp_info["Sitzung"]
fmri_mode   = exp_info["fMRI-Modus"]

os.makedirs(DATA_DIR, exist_ok=True)
date_str   = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
data_fname = _p("data", f"{participant}_ses{session}_{date_str}_OLMM_A.csv")

# ── Window & clock ─────────────────────────────────────────────────────────────
# Copied verbatim from OLM_Set_A_english_orig.py
win = visual.Window(size=(1280,720), fullscr=True,
                    color=(0,0,0), colorSpace="rgb255",
                    units="pix", allowGUI=False)
global_clock = core.Clock()

# ── Visual objects ─────────────────────────────────────────────────────────────
# Copied verbatim from OLM_Set_A_english_orig.py
fix_stim  = visual.TextStim(win, text="+", color="white", height=80, pos=(0,0))
feed_text = visual.TextStim(win, text="",  color="white", height=50, pos=(0,350),
                            wrapWidth=1100)
main_img  = visual.ImageStim(win, pos=(0,-70), size=(1024,787))
feed_img  = visual.ImageStim(win, pos=(0,-70), size=(1024,787))
afc_img   = visual.ImageStim(win, pos=(0,  0), size=(1224,987))

key_label_left  = visual.TextStim(win, text="<- Ja",   color="white", height=40,
                                  pos=(-340,-490), wrapWidth=600)
key_label_right = visual.TextStim(win, text="Nein ->", color="white", height=40,
                                  pos=( 340,-490), wrapWidth=600)

# Bubble / info screen image (600×398, centred)
bub_img = visual.ImageStim(win, pos=(0, 0), size=(600, 398))

# ── Data writer ────────────────────────────────────────────────────────────────
_csv_file   = open(data_fname, "w", newline="", encoding="utf-8")
_csv_writer = csv.writer(_csv_file)
_csv_writer.writerow(["Teilnehmer","Sitzung","Set",
                      "Phase","Block","Wdh","Versuch",
                      "Stimulus","StimTyp","Richtung","Seite",
                      "Antwort","Korrekt","RT","Onset",
                      "RealisierteBlockReihenfolge"])

def write_row(**kw):
    _csv_writer.writerow([participant, session, "A",
        kw.get("Phase",""), kw.get("Block",""), kw.get("Wdh",""), kw.get("Versuch",""),
        kw.get("Stimulus",""), kw.get("StimTyp",""),
        kw.get("Richtung",""), kw.get("Seite",""),
        kw.get("Antwort",""), kw.get("Korrekt",""),
        kw.get("RT",""), kw.get("Onset",""),
        kw.get("RealisierteBlockReihenfolge","")])
    _csv_file.flush()

# ── Helpers ────────────────────────────────────────────────────────────────────
def check_quit():
    if event.getKeys(keyList=["escape"]):
        _csv_file.close(); win.close(); core.quit()

def show_fixation(duration=FIX_DUR):
    fix_stim.draw(); win.flip(); core.wait(duration); check_quit()

def get_stimuli(directory):
    """Return sorted list of .jpg/.JPG files, excluding Thumbs.*."""
    files = sorted(glob.glob(os.path.join(directory,"*.jpg")) +
                   glob.glob(os.path.join(directory,"*.JPG")))
    return [f for f in files
            if not os.path.basename(f).lower().startswith("thumbs")]

def parse_stim_name(filename):
    """Extract metadata from filename like h24_p33_i_up_left.jpg."""
    base  = os.path.splitext(os.path.basename(filename))[0]
    parts = base.split("_")
    try:
        return {"house": parts[0], "pos": parts[1], "stim_type": parts[2],
                "direction": parts[3], "side": parts[-1]}
    except IndexError:
        return {"house": base, "pos":"", "stim_type":"", "direction":"", "side":""}

def pair_stimuli(all_files):
    """Pair each _k_ (key/correct) file with its _i_ (foils) siblings."""
    k_files = [f for f in all_files if "_k_" in os.path.basename(f)]
    i_files = [f for f in all_files if "_i_" in os.path.basename(f)]
    pairs = []
    for kf in k_files:
        hid   = parse_stim_name(kf)["house"]
        foils = [f for f in i_files if parse_stim_name(f)["house"] == hid]
        pairs.append({"correct": kf, "foils": foils,
                      "meta": parse_stim_name(kf)})
    return pairs

def shuffle_no_repeat(items, key_fn):
    """Shuffle list so no two consecutive items share the same key_fn value."""
    items = items[:]
    random.shuffle(items)
    for _ in range(200):
        ok = True
        for i in range(1, len(items)):
            if key_fn(items[i]) == key_fn(items[i-1]):
                ok = False
                j = random.randint(i, len(items)-1)
                items[i], items[j] = items[j], items[i]
        if ok: break
    return items

def show_text_slide(title, body, footer="[LEERTASTE zum Fortfahren]", advance_key="space"):
    """Render a text instruction slide on a black background."""
    visual.TextStim(win, text=title, color="white", height=36,
                    bold=True, pos=(0, 280), wrapWidth=1100).draw()
    visual.Line(win, start=(-540, 240), end=(540, 240),
                lineColor="white", lineWidth=1).draw()
    visual.TextStim(win, text=body, color="white", height=28,
                    pos=(0, 20), wrapWidth=1050, alignText="left").draw()
    visual.TextStim(win, text=footer, color="white", height=22,
                    pos=(0, -295), wrapWidth=1100).draw()
    win.flip()
    event.waitKeys(keyList=[advance_key, "escape"]); check_quit()

# ── Block-order shuffling ──────────────────────────────────────────────────────
# Matches 03_learning.sce lines 401-424:
#   order[] = {"learning-1","learning-2","learning-3","learning-4","control","control"}
#   shuffled so: first block not control AND no two adjacent identical types
#   the two control blocks get assigned "control-1"/"control-2" in shuffled order
def shuffle_block_order(orders):
    """Shuffle block order with the PCL's two constraints."""
    while True:
        random.shuffle(orders)
        ok = True
        if orders[0] == "control":
            ok = False
        for x in range(1, len(orders)):
            if orders[x-1] == orders[x]:
                ok = False
                break
        if ok: break
    return orders

def show_bubble_screen(bubble_name):
    """Show a bubble/info screen for BUBBLE_DUR (4.5 s)."""
    bub_path = os.path.join(STIM_BUBBLES, bubble_name)
    bub_img.setImage(bub_path)
    bub_img.draw(); win.flip()
    core.wait(BUBBLE_DUR); check_quit()

def show_block_intro(block_type):
    """3 × fixation (4500 ms) + bubble screen, matching PCL block intro."""
    bubble = "learning.png" if block_type == "learning" else "control.png"
    for _ in range(3):
        show_fixation(FIX_DUR)
    show_bubble_screen(bubble)

# ── Trial runners ──────────────────────────────────────────────────────────────

def run_learning_trial(img_path, phase="learning", block=1, rep=1,
                       trial_idx=1, all_pairs=None):
    """
    Phase 1 (TRIAL_DUR = 2.5 s):
        Map image shown; key labels visible in behavioural mode.
        Response collected any time during the window; window runs to end.
    Phase 2 (FEEDBACK_DUR = 2.0 s):
        Feedback text + correct-position (_k_) image.
    """
    meta  = parse_stim_name(img_path)
    fname = os.path.basename(img_path)

    # Phase 1 ────────────────────────────────────────────────────────────────
    main_img.setImage(img_path)
    main_img.draw()
    if not fmri_mode:
        key_label_left.draw()
        key_label_right.draw()
    win.flip()
    onset = global_clock.getTime()

    event.clearEvents()
    resp_clock = core.Clock()
    response = rt = None
    while resp_clock.getTime() < TRIAL_DUR:
        keys = event.getKeys(keyList=["left","right","escape"],
                             timeStamped=resp_clock)
        if keys:
            key, t = keys[0]
            if key == "escape":
                _csv_file.close(); win.close(); core.quit()
            response, rt = key, t
            break
        check_quit()

    # Wait out remainder of stimulus window
    elapsed = resp_clock.getTime()
    if elapsed < TRIAL_DUR:
        core.wait(TRIAL_DUR - elapsed)

    # Correctness: code 1 (left) on _k_ = correct; code 2 (right) on _i_ = correct
    is_k = "_k_" in fname
    resp_code = 1 if response == "left" else (2 if response == "right" else 0)
    if resp_code == 0:
        correct_flag = "timeout";   fb_label = "Zu spat!"
    elif (is_k and resp_code == 1) or (not is_k and resp_code == 2):
        correct_flag = "correct";   fb_label = "Richtig!"
    else:
        correct_flag = "incorrect"; fb_label = "Falsch!"

    # Find _k_ feedback image
    correct_fb = img_path
    if all_pairs:
        for pair in all_pairs:
            if pair["correct"] == img_path or img_path in pair["foils"]:
                correct_fb = pair["correct"]; break

    # Phase 2 ────────────────────────────────────────────────────────────────
    feed_text.text = f"{fb_label}   Die korrekte Position ist:"
    feed_img.setImage(correct_fb)
    feed_text.draw(); feed_img.draw()
    win.flip()
    core.wait(FEEDBACK_DUR)
    check_quit()

    write_row(Phase=phase, Block=block, Wdh=rep, Versuch=trial_idx,
              Stimulus=fname, StimTyp=meta["stim_type"],
              Richtung=meta["direction"], Seite=meta["side"],
              Antwort=response, Korrekt=correct_flag,
              RT=round(rt,4) if rt else "", Onset=round(onset,4))


def run_control_trial(img_path, phase="control", block=1, rep=1, trial_idx=1,
                      question_right=True):
    """
    Single-screen control trial (manifest review-corrected):
    Image + question text + key labels for TRIAL_DUR (2.5 s), then
    feedback text + same image for FEEDBACK_DUR (2.0 s).
    question_right=True  → "Ist das Haus auf der rechten Seite?"
    question_right=False → "Ist das Haus auf der linken Seite?"
    """
    meta  = parse_stim_name(img_path)
    fname = os.path.basename(img_path)

    # Phase 1: image + question ──────────────────────────────────────────────
    if question_right:
        feed_text.text = "Ist das Haus auf der rechten Seite?"
    else:
        feed_text.text = "Ist das Haus auf der linken Seite?"
    feed_img.setImage(img_path)
    feed_text.draw(); feed_img.draw()
    if not fmri_mode:
        key_label_left.draw()
        key_label_right.draw()
    win.flip()
    onset = global_clock.getTime()

    event.clearEvents()
    resp_clock = core.Clock()
    response = rt = None
    while resp_clock.getTime() < TRIAL_DUR:
        keys = event.getKeys(keyList=["left","right","escape"],
                             timeStamped=resp_clock)
        if keys:
            key, t = keys[0]
            if key == "escape":
                _csv_file.close(); win.close(); core.quit()
            response, rt = key, t
            break
        check_quit()

    elapsed = resp_clock.getTime()
    if elapsed < TRIAL_DUR:
        core.wait(TRIAL_DUR - elapsed)

    is_right  = meta["side"] == "right"
    resp_code = 1 if response == "left" else (2 if response == "right" else 0)
    fb_answer_right = ("Das Haus ist auf der rechten Seite."
                       if is_right else "Das Haus ist nicht auf der rechten Seite.")
    fb_answer_left  = ("Das Haus ist auf der linken Seite."
                       if is_right else "Das Haus ist nicht auf der linken Seite.")

    if question_right:
        fb_answer = fb_answer_right
    else:
        fb_answer = fb_answer_left

    if resp_code == 0:
        correct_flag = "timeout";   fb_label = "Zu spat!"
    elif (is_right and resp_code == 1) or (not is_right and resp_code == 2):
        correct_flag = "correct";   fb_label = "Richtig!"
    else:
        correct_flag = "incorrect"; fb_label = "Falsch!"

    # Phase 2: feedback ──────────────────────────────────────────────────────
    feed_text.text = f"{fb_label}   {fb_answer}"
    feed_text.draw(); feed_img.draw()
    win.flip()
    core.wait(FEEDBACK_DUR)
    check_quit()

    write_row(Phase=phase, Block=block, Wdh=rep, Versuch=trial_idx,
              Stimulus=fname, StimTyp=meta["stim_type"],
              Richtung=meta["direction"], Seite=meta["side"],
              Antwort=response, Korrekt=correct_flag,
              RT=round(rt,4) if rt else "", Onset=round(onset,4))


def run_afc_trial(img_path, trial_idx=1):
    """3-AFC: composite image, keys 1/2/3, no time limit."""
    fname = os.path.basename(img_path)
    event.clearEvents()
    afc_img.setImage(img_path); afc_img.draw(); win.flip()
    onset = global_clock.getTime()
    keys  = event.waitKeys(keyList=["1","2","3","escape"])
    rt    = global_clock.getTime() - onset
    if "escape" in keys:
        _csv_file.close(); win.close(); core.quit()
    write_row(Phase="AFC", Versuch=trial_idx, Stimulus=fname,
              Antwort=keys[0], RT=round(rt,4), Onset=round(onset,4))


# ── Block runners ──────────────────────────────────────────────────────────────

def run_learning_block(block_dir, block_num, n_reps=4):
    """Run a learning block with 4 repetitions (LS1–LS4)."""
    files = get_stimuli(block_dir)
    pairs = pair_stimuli(files)

    # Interleave up/down houses (from reference implementation)
    random.shuffle(pairs)
    ups   = [p for p in pairs if p["meta"]["direction"] == "up"]
    downs = [p for p in pairs if p["meta"]["direction"] == "down"]
    interleaved = []
    for u, d in zip(ups, downs):
        interleaved += [u, d]
    interleaved += ups[len(downs):] + downs[len(ups):]
    pairs = interleaved

    # Build flat stimulus list: correct + foils per pair
    stim_list = []
    for pair in pairs:
        stim_list.append(pair["correct"])
        stim_list.extend(pair["foils"])

    for rep in range(1, n_reps + 1):
        shuffled = shuffle_no_repeat(stim_list,
                                     key_fn=lambda f: parse_stim_name(f)["house"])
        for t_idx, img in enumerate(shuffled, 1):
            run_learning_trial(img, phase=f"learning-{block_num}",
                               block=block_num, rep=rep,
                               trial_idx=t_idx, all_pairs=pairs)
        show_fixation(FIX_DUR)


def run_control_block(block_dir, block_num, n_reps=4, question_right=True):
    """Run a control block with 4 repetitions."""
    stim_list = get_stimuli(block_dir)
    for rep in range(1, n_reps + 1):
        shuffled = shuffle_no_repeat(stim_list,
                                     key_fn=lambda f: parse_stim_name(f)["house"])
        for t_idx, img in enumerate(shuffled, 1):
            run_control_trial(img, phase=f"control-{block_num}",
                              block=block_num, rep=rep, trial_idx=t_idx,
                              question_right=question_right)
        show_fixation(FIX_DUR)


# ── Practice block ─────────────────────────────────────────────────────────────
def run_practice_block():
    """
    Practice with feedback (40 trials, 20 unique images × 2 repetitions).
    The PCL pairs each _k_ file with _i_ files sharing the same house prefix,
    but the prac/ directory is MISSING from this repo (see manifest unresolved).
    We load from learning/block1 as a fallback and use the first 10 pairs.
    NOTE: This is a workaround for the missing prac/ directory.
    """
    # Fallback: use learning/block1 images for practice
    files = get_stimuli(STIM_LEARN_DIRS[0])
    pairs = pair_stimuli(files)[:10]  # use first 10 pairs

    # Build one_Ten: each pair contributes 2 images (correct + first foil)
    one_ten = []
    for pair in pairs:
        one_ten.append(pair["correct"])
        if pair["foils"]:
            one_ten.append(pair["foils"][0])

    for rep in range(1, 3):  # 2 repetitions with reshuffle
        random.shuffle(one_ten)
        for t_idx, img in enumerate(one_ten, 1):
            run_learning_trial(img, phase="practice", block="prac",
                               rep=rep, trial_idx=t_idx, all_pairs=pairs)
        show_fixation(FIX_DUR)


# ── Instructions ───────────────────────────────────────────────────────────────

def show_instructions_part1():
    """8 text slides for the learning phase (German)."""
    show_text_slide(
        title="Willkommen – OLMM Studie",
        body=(
            "Vielen Dank für Ihre Teilnahme!\n\n"
            "Bei dieser Aufgabe lernen Sie, wo Häuser auf einer Karte位置iert sind.\n\n"
            "Ihre Aufgabe ist es, sich die genaue Position\n"
            "jedes Hauses zu merken."
        ),
        footer="Folie 1 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Was Sie sehen werden",
        body=(
            "Sie sehen ein Bild, das ein Haus auf einer Karte zeigt.\n\n"
            "Das Haus ist entweder in der KORREKTEN Position\n"
            "oder in einer FALSCHEN Position.\n\n"
            "Ihre Aufgabe: Entscheiden Sie, ob das Haus\n"
            "an der richtigen Position ist."
        ),
        footer="Folie 2 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Tasten",
        body=(
            "Drücken Sie:\n\n"
            "  PFEIL NACH LINKS   <-  JA, das ist die korrekte Position\n\n"
            "  PFEIL NACH RECHTS  ->  NEIN, das ist nicht die korrekte Position\n\n"
            "Sie haben 2,5 Sekunden pro Bild.\n"
            "Antworten Sie so schnell und genau wie möglich."
        ),
        footer="Folie 3 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Feedback",
        body=(
            "Nach jeder Antwort sehen Sie ein Feedback:\n\n"
            "  'Richtig!'   – Ihre Antwort war korrekt\n\n"
            "  'Falsch!'    – Ihre Antwort war nicht korrekt\n\n"
            "  'Zu spat!'   – Sie haben nicht rechtzeitig geantwortet\n\n"
            "Sie sehen auch die korrekte Position des Hauses."
        ),
        footer="Folie 4 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Lernwiederholungen",
        body=(
            "Jedes Haus wird mehrmals gezeigt.\n\n"
            "Beim ersten Mal werden Sie die korrekte Position noch nicht kennen –\n"
            "das ist normal. Nutzen Sie das Feedback zum Lernen.\n\n"
            "Mit jeder Wiederholung sollte es einfacher werden,\n"
            "die korrekte Position zu erkennen."
        ),
        footer="Folie 5 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Kontrol-aufgabe",
        body=(
            "Zwischendurch gibt es auch eine Kontrol-aufgabe.\n\n"
            "Sie sehen den gleichen Bildtyp und beantworten die Frage:\n\n"
            "  'Ist das Haus auf der rechten Seite des Bildes?'\n\n"
            "Auch hier: PFEIL NACH LINKS = JA, PFEIL NACH RECHTS = NEIN.\n\n"
            "Schauen Sie sich das Bild an – kein räumliches Gedachtnis erforderlich."
        ),
        footer="Folie 6 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Wichtige Hinweise",
        body=(
            "Versuchen Sie, sich die POSITION jedes Hauses auf der Karte zu merken,\n"
            "nicht nur wie das Haus aussieht.\n\n"
            "Diese Aufgabe misst das Raumgedachtnis –\n"
            "wo genau auf der Karte befindet sich das Haus?\n\n"
            "Antworten Sie so schnell und genau wie möglich."
        ),
        footer="Folie 7 / 8   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Bereit?",
        body=(
            "Sie sind jetzt bereit, die Aufgabe zu beginnen.\n\n"
            "Zur Erinnerung:\n"
            "  PFEIL NACH LINKS  <-  JA  (korrekte Position)\n"
            "  PFEIL NACH RECHTS ->  NEIN  (falsche Position)\n\n"
            "Sie haben 2,5 Sekunden pro Bild.\n\n"
            "Viel Erfolg!"
        ),
        footer="Folie 8 / 8   [LEERTASTE -> Start]",
        advance_key="space"
    )


def show_instructions_part2():
    """4 text slides for the AFC recognition test (German)."""
    show_text_slide(
        title="Gedachtnistest",
        body=(
            "Sie haben alle Lernblöcke abgeschlossen.\n\n"
            "Es folgt jetzt ein Gedachtnistest.\n\n"
            "Sie werden Bilder mit drei verschiedenen Positionen desselben Hauses sehen.\n"
            "Nur eine Position war korrekt – welche war es?"
        ),
        footer="Folie 1 / 4   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Gedachtnistest – Ihre Aufgabe",
        body=(
            "Wahlen Sie von den drei gezeigten Positionen\n"
            "die Position aus, die Sie während der Lernphase gelernt haben.\n\n"
            "Drücken Sie:\n\n"
            "       1  →  linke Position\n"
            "       2  →  mittlere Position\n"
            "       3  →  rechte Position"
        ),
        footer="Folie 2 / 4   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Gedachtnistest – Hinweise",
        body=(
            "Es gibt keine Zeitbegrenzung.\n\n"
            "Antworten Sie so genau wie möglich.\n\n"
            "Wenn Sie unsicher sind, raten Sie –\n"
            "lassen Sie kein Bild unbeantwortet."
        ),
        footer="Folie 3 / 4   [LEERTASTE -> fortsetzen]"
    )
    show_text_slide(
        title="Gedachtnistest – Bereit?",
        body=(
            "Der Gedachtnistest beginnt gleich.\n\n"
            "Zur Erinnerung:\n\n"
            "       1  →  linke Position\n"
            "       2  →  mittlere Position\n"
            "       3  →  rechte Position\n\n"
            "Viel Erfolg!"
        ),
        footer="Folie 4 / 4   [LEERTASTE -> Start]",
        advance_key="space"
    )


# ── Main experiment ────────────────────────────────────────────────────────────

# 00  Instructions Part 1
show_instructions_part1()

# ── Build block schedule ───────────────────────────────────────────────────────
# Manifest: runtime shuffle with PCL constraints.
# The manifest records the realised order in the CSV.

block_types = ["learning-1", "learning-2", "learning-3", "learning-4",
               "control-1", "control-2"]

# Determine learning vs control for constraint
is_control = lambda name: name.startswith("control")

# Shuffle with PCL constraints
random.shuffle(block_types)
for _ in range(500):
    ok = True
    if is_control(block_types[0]):
        ok = False
    for x in range(1, len(block_types)):
        type_a = "control" if is_control(block_types[x-1]) else "learning"
        type_b = "control" if is_control(block_types[x]) else "learning"
        if type_a == type_b:
            ok = False
            break
    if ok: break
    random.shuffle(block_types)

# Log the realised order
realised_order = block_types
# Write realised order to first row(s) — we add it to every row
# via write_row's realised_block_order field

# 01  Practice block (before learning, matching reference structure)
run_practice_block()
show_fixation(FIX_DUR)

# Process block schedule
for bt in block_types:
    # Show block intro
    block_type_category = "learning" if bt.startswith("learning") else "control"
    show_block_intro(block_type_category)

    if bt == "learning-1":
        run_learning_block(STIM_LEARN_DIRS[0], block_num=1)
    elif bt == "learning-2":
        run_learning_block(STIM_LEARN_DIRS[1], block_num=2)
    elif bt == "learning-3":
        run_learning_block(STIM_LEARN_DIRS[2], block_num=3)
    elif bt == "learning-4":
        run_learning_block(STIM_LEARN_DIRS[3], block_num=4)
    elif bt == "control-1":
        run_control_block(STIM_CTRL_DIRS[0], block_num=1, question_right=True)
    elif bt == "control-2":
        run_control_block(STIM_CTRL_DIRS[1], block_num=2, question_right=False)

# 07  Instructions Part 2 (AFC)
show_instructions_part2()

# 08  AFC Test
afc_files = get_stimuli(STIM_AFC_DIR)
random.shuffle(afc_files)
for t_idx, img in enumerate(afc_files, 1):
    run_afc_trial(img, trial_idx=t_idx)

# End screen
visual.TextStim(win, text="Die Aufgabe ist beendet.\nVielen Dank!",
                color="white", height=60, wrapWidth=1100).draw()
win.flip()
event.waitKeys(keyList=["space","return","escape"])

_csv_file.close(); win.close(); core.quit()
