#!/usr/bin/env python3
"""
check_paradigm.py — does this PsychoPy script actually run? Generic.

Replaces the removed Agent/05_Paradigm/check_runs.sh + lint_style.sh.

    python3 Agent/tools/check_paradigm.py "<script.py>"
    python3 Agent/tools/check_paradigm.py "<script.py>" --launch
    python3 Agent/tools/check_paradigm.py "<script.py>" --generated

Three checks, cheapest first; it stops at the first hard failure.

  1. compile      py_compile — does it parse?
  2. assets       every path-like string literal the script opens: does the file
                  exist, case-sensitively? (Linux is; the acquisition machines
                  were not.)
  3. launch       --launch only: run it headless with a short timeout. Proves
                  imports resolve and a window opens. Does NOT prove the trials
                  or timing are right.

--generated additionally applies the BEEHub house style rules, which bind
GENERATED code only — never a human-made reference or a project's original
PsychoPy files.

Exit: 0 pass, 1 findings, 2 usage error.
"""

from __future__ import annotations

import argparse
import ast
import os
import pathlib
import py_compile
import re
import subprocess
import sys
import tempfile

# House-style rules (generated code only)
NORM_UNITS = re.compile(r"units\s*=\s*['\"](norm|height|deg)['\"]")
DEPRECATED_ALIGN = re.compile(r"\b(alignHoriz|alignVert)\s*=")
FRACTIONAL = re.compile(r"\b(height|wrapWidth)\s*=\s*(0?\.\d+)\b")
TRIGGER = re.compile(r"\b(parallel|ParallelPort|LPT)\b")
PROVENANCE = "AUTO-GENERATED by BEEHub"

ASSET_SUFFIX = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".wav", ".mp3", ".ogg",
                ".mp4", ".xlsx", ".xls", ".csv", ".tsv"}


def findings_for_assets(path: pathlib.Path, tree: ast.AST) -> list[str]:
    """Every string literal that looks like an asset path: does it exist?"""
    out: list[str] = []
    seen: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Constant) or not isinstance(node.value, str):
            continue
        s = node.value
        if s in seen or len(s) > 300 or "\n" in s:
            continue
        if pathlib.PurePath(s).suffix.lower() not in ASSET_SUFFIX:
            continue
        seen.add(s)
        if s.startswith(("http://", "https://")) or "{" in s or "%s" in s:
            continue
        target = (path.parent / s)
        if target.exists():
            continue
        # Case-insensitive retry: catches Windows-authored paths on Linux.
        parent = target.parent
        if parent.is_dir():
            lower = {p.name.lower(): p.name for p in parent.iterdir()}
            hit = lower.get(target.name.lower())
            if hit:
                out.append(f"line {node.lineno}: '{s}' — exists but as '{hit}' "
                           "(case mismatch; Linux is case-sensitive)")
                continue
        out.append(f"line {node.lineno}: '{s}' — not found relative to the script")
    return out


def findings_for_style(text: str) -> list[str]:
    out: list[str] = []
    for m in NORM_UNITS.finditer(text):
        out.append(f"line {text[:m.start()].count(chr(10))+1}: units='{m.group(1)}' "
                   "— house style is units='pix' only")
    for m in DEPRECATED_ALIGN.finditer(text):
        out.append(f"line {text[:m.start()].count(chr(10))+1}: {m.group(1)}= "
                   "raises at runtime — use alignText/anchorHoriz/anchorVert")
    for m in FRACTIONAL.finditer(text):
        out.append(f"line {text[:m.start()].count(chr(10))+1}: {m.group(1)}={m.group(2)} "
                   "— value in (-1,1) is a norm unit; pixels expected")
    for m in TRIGGER.finditer(text):
        out.append(f"line {text[:m.start()].count(chr(10))+1}: '{m.group(1)}' "
                   "— no trigger hardware in BEEHub; remove")
    if PROVENANCE not in text:
        out.append("no provenance header naming the source and model")
    if "ImageStim(" in text:
        for m in re.finditer(r"ImageStim\(((?:[^()]|\([^()]*\))*)\)", text, re.S):
            if "size" not in m.group(1):
                out.append(f"line {text[:m.start()].count(chr(10))+1}: "
                           "ImageStim without an explicit size= in pixels")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("script")
    ap.add_argument("--launch", action="store_true",
                    help="also run it headless (needs the psychopy env)")
    ap.add_argument("--generated", action="store_true",
                    help="apply house-style rules (generated code only)")
    ap.add_argument("--timeout", type=int, default=45)
    args = ap.parse_args()

    path = pathlib.Path(args.script)
    if not path.is_file():
        print(f"no such file: {path}", file=sys.stderr)
        return 2

    print(f"# Paradigm gate — {path}\n")
    text = path.read_text(encoding="utf-8", errors="replace")

    # 1. compile -------------------------------------------------------------
    if text.startswith("\ufeff"):
        print("FAIL compile — file starts with a UTF-8 BOM (U+FEFF), which is a "
              "syntax error in Python.\n     fix: sed -i '1s/^\\xEF\\xBB\\xBF//' "
              f'"{path}"')
        return 1
    try:
        py_compile.compile(str(path), cfile=tempfile.mktemp(), doraise=True)
        print("ok   compile")
    except py_compile.PyCompileError as e:
        print(f"FAIL compile — {str(e).strip().splitlines()[-1]}")
        return 1

    problems = 0

    # 2. assets --------------------------------------------------------------
    asset = findings_for_assets(path, ast.parse(text))
    if asset:
        problems += len(asset)
        print(f"FAIL assets — {len(asset)} referenced file(s) missing")
        for a in asset:
            print(f"     {a}")
    else:
        print("ok   assets")

    # 3. house style ---------------------------------------------------------
    if args.generated:
        style = findings_for_style(text)
        if style:
            problems += len(style)
            print(f"FAIL style — {len(style)} house-style violation(s)")
            for a in style:
                print(f"     {a}")
        else:
            print("ok   style")

    # 4. launch --------------------------------------------------------------
    if args.launch:
        if asset:
            print("skip launch — fix the missing assets first, it will only "
                  "fail on them")
        else:
            env = dict(os.environ, PSYCHOPY_HEADLESS="1", SDL_VIDEODRIVER="dummy")
            try:
                p = subprocess.run([sys.executable, path.name], cwd=path.parent,
                                   capture_output=True, text=True,
                                   timeout=args.timeout, env=env)
                if p.returncode == 0:
                    print("ok   launch")
                else:
                    problems += 1
                    tail = (p.stderr or p.stdout).strip().splitlines()
                    print(f"FAIL launch — exit {p.returncode}")
                    for line in tail[-6:]:
                        print(f"     {line[:160]}")
            except subprocess.TimeoutExpired:
                # A paradigm that waits for a keypress is alive, not broken.
                print(f"ok   launch — still running after {args.timeout}s "
                      "(no immediate crash; likely waiting for input)")
            except OSError as e:
                print(f"FAIL launch — could not start: {e}")
                problems += 1
    else:
        print("note launch not attempted — re-run with --launch inside the "
              "psychopy env to prove it actually starts")

    print()
    if problems:
        print(f"{problems} finding(s). The gate has NOT passed.")
        return 1
    print("gate passed. This proves it starts — NOT that trials or timing are "
          "correct. A human still has to run it and click through.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
